server:
  port: 8081
  context-path: /client1
  session:
    cookie:
      name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: client1
      clientSecret: clientSecret1
      accessTokenUri: http://localhost:8080/auth/oauth/token
      userAuthorizationUri: http://localhost:8080/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8080/auth/user/me
spring:
  thymeleaf:
    cache: false
